apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: diegofacundopereznicolau/users-service:latest
          ports:
            - containerPort: 50052
          env:
            - name: DB_HOST
              value: mysql-users
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-service
  ports:
    - port: 50052