// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: catalog/catalog.proto

package catalogpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogRequest) Reset() {
	*x = GetCatalogRequest{}
	mi := &file_catalog_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogRequest) ProtoMessage() {}

func (x *GetCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *GetCatalogRequest) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantId  int32                  `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Nombre        string                 `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Descripcion   string                 `protobuf:"bytes,4,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	Precio        float64                `protobuf:"fixed64,5,opt,name=precio,proto3" json:"precio,omitempty"`
	Disponible    bool                   `protobuf:"varint,6,opt,name=disponible,proto3" json:"disponible,omitempty"`
	Categoria     string                 `protobuf:"bytes,7,opt,name=categoria,proto3" json:"categoria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_catalog_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *Product) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Product) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *Product) GetPrecio() float64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Product) GetDisponible() bool {
	if x != nil {
		return x.Disponible
	}
	return false
}

func (x *Product) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

type GetCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogResponse) Reset() {
	*x = GetCatalogResponse{}
	mi := &file_catalog_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogResponse) ProtoMessage() {}

func (x *GetCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogResponse) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetCatalogResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_catalog_catalog_proto protoreflect.FileDescriptor

const file_catalog_catalog_proto_rawDesc = "" +
	"\n" +
	"\x15catalog/catalog.proto\x12\acatalog\"8\n" +
	"\x11GetCatalogRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\"\xce\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\x05R\frestaurantId\x12\x16\n" +
	"\x06nombre\x18\x03 \x01(\tR\x06nombre\x12 \n" +
	"\vdescripcion\x18\x04 \x01(\tR\vdescripcion\x12\x16\n" +
	"\x06precio\x18\x05 \x01(\x01R\x06precio\x12\x1e\n" +
	"\n" +
	"disponible\x18\x06 \x01(\bR\n" +
	"disponible\x12\x1c\n" +
	"\tcategoria\x18\a \x01(\tR\tcategoria\"B\n" +
	"\x12GetCatalogResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.catalog.ProductR\bproducts2c\n" +
	"\x0eCatalogService\x12Q\n" +
	"\x16GetCatalogByRestaurant\x12\x1a.catalog.GetCatalogRequest\x1a\x1b.catalog.GetCatalogResponseB\x1aZ\x18delivery-proto/catalogpbb\x06proto3"

var (
	file_catalog_catalog_proto_rawDescOnce sync.Once
	file_catalog_catalog_proto_rawDescData []byte
)

func file_catalog_catalog_proto_rawDescGZIP() []byte {
	file_catalog_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_catalog_proto_rawDesc), len(file_catalog_catalog_proto_rawDesc)))
	})
	return file_catalog_catalog_proto_rawDescData
}

var file_catalog_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_catalog_catalog_proto_goTypes = []any{
	(*GetCatalogRequest)(nil),  // 0: catalog.GetCatalogRequest
	(*Product)(nil),            // 1: catalog.Product
	(*GetCatalogResponse)(nil), // 2: catalog.GetCatalogResponse
}
var file_catalog_catalog_proto_depIdxs = []int32{
	1, // 0: catalog.GetCatalogResponse.products:type_name -> catalog.Product
	0, // 1: catalog.CatalogService.GetCatalogByRestaurant:input_type -> catalog.GetCatalogRequest
	2, // 2: catalog.CatalogService.GetCatalogByRestaurant:output_type -> catalog.GetCatalogResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_catalog_catalog_proto_init() }
func file_catalog_catalog_proto_init() {
	if File_catalog_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_catalog_proto_rawDesc), len(file_catalog_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_catalog_proto_msgTypes,
	}.Build()
	File_catalog_catalog_proto = out.File
	file_catalog_catalog_proto_goTypes = nil
	file_catalog_catalog_proto_depIdxs = nil
}
