apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-auth
  template:
    metadata:
      labels:
        app: mysql-auth
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "201504070"
            - name: MYSQL_DATABASE
              value: "auth_db"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-auth
spec:
  selector:
    app: mysql-auth
  ports:
    - port: 3306